### ISSUE TITLE
Add CSS Animations

### ISSUE THREAD

**Issue by iamkrvikash** [iamkrvikash/css-animations#4]
Rules -

Creator folder with Number_Css_animated_folder_name Eg. (8_Ghost_Loading)
In the folder ,
Add two files 
- index.html
- style.css
- Related images or videos
- No javascript to be used.

Check your PR passes the above list.
Then ,Push PR 

👍Thanks for contributing.

**Comment by itsPrajapat** [comment]
Could You please assign this to me

**Comment by iamkrvikash** [comment]
@itsPrajapat Done 👍

**Comment by itsPrajapat** [comment]
> @itsPrajapat Done 👍

I have made a PR please accept it.
